#! /bin/sh

# configure-windows
#
# Creates a native Windows MingW build, based on:
# https://github.com/ocaml/ocaml/blob/trunk/README.win32.adoc


export prefix=C:/ocamlmgw64
while : ; do
    case "$1" in
        "") break;;
        -prefix|--prefix)
            prefix=$2; shift;;
    esac
    shift
done

echo "[configure-windows] Setting up flexdll"
./clone-flexdll
./configure --build=x86_64-unknown-cygwin --host=x86_64-w64-mingw32 --prefix=$prefix
make flexdll
