#! /usr/bin/env bash

# esy-build
#
# Wrapper to execute appropriate build strategy, based on platform

set -u
set -e
set -o pipefail

case "$(uname -s)" in
    CYGWIN*|MINGW32*|MSYS*)
        echo "[esy-build] Detected windows environment..."
        make -j4 world.opt
        make flexlink.opt
        ;;
    *)
        echo "[esy-build] Detected OSX / Linux environment"
        make -j4 world.opt
        ;;
esac

# Common build steps
make install