#!/usr/bin/env bash
# Copyright (c) 2016-present, Facebook, Inc. All rights reserved.

re='(.*)@(.*)@(.*)'
replaced=${1%.in}
echo "" > $replaced
cat $1 | while IFS='' read line
do
    while [[ $line =~ $re ]]; do
        line=${BASH_REMATCH[1]}$(eval echo "\$${BASH_REMATCH[2]}")${BASH_REMATCH[3]}
    done
    echo "$line" >> $replaced
done
